### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by ehaupt** [mkirchner/tcping#1]
Could you please [tag](https://help.github.com/en/articles/creating-releases) the imported code as version '1.3.5'?

That would make it easier for package maintainers linking to the new GitHub project home.

Thank you in advance.

**Comment by mkirchner** [comment]
@ehaupt, thanks for bringing this up. Tagged and also re-released under MIT.

**Comment by ehaupt** [comment]
Thank you very much :+1:
