### ISSUE TITLE
Continuous monitoring

### ISSUE THREAD

**Issue by theunf** [mkirchner/tcping#2]
I use your tool thru brew at MacOs.

  Please add options to do continuous monitoring and which interval to repeat tcping after an open port result ! 

  Also would be good to have a flags to do something when tcp port is closed :
    - sound a beep for interactive monitoring
       and/or
    - run a script

  Would be awesome!

  Last, how about also support udp ?

**Comment by mkirchner** [comment]
Hi @theunf ,
thanks for using `tcping`!
Everything you're asking for can be implemented using simple shell scripting around the existing tool.

1. For continuous monitoring use eg. `while true; do tcping -t 2 192.168.0.1 443; sleep 60; done` or use the `watch` command (also available via brew).
2. For actions depending on the ping result, check the return value: `tcping -t 2 192.168.0.1 443 || say beep`.
3. UDP has no concept of connections, all you can do is check if you get an *ICMP destination unreachable* message, which is generally dropped by internet-facing firewalls. If you still want to do this, I recommend you use `netcat`.

HTH!
